version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
    schedule:
      interval: 'monthly'
      day: 'sunday'
      time: '16:00'
      timezone: 'America/Guayaquil'
    versioning-strategy: 'increase'
    open-pull-requests-limit: 3
